### ISSUE TITLE
Allergien und Unverträglichkeiten in ISiK (AG Stufe 4)

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Medikation#83]
Externe Anfrage mit folgender Anforderung: Szenarien rund um Allergien und Unverträglichkeiten sollten in ISiK abgedeckt werden.

---
Ursprüngliche Anfrage (ANFISK-61) :

wir benötigen im nationalen Kontext für die Patientensicherheit neben dem ISIK2-Medikamentenprofil eben auch ein solches für Allergien und Unverträglichkeiten. Die Querverlinkung in den Medikamentenstamm des vom Bfam herausgegebenen Katalogs der Medikamente wäre dringlich zu empfehlen. Ebenso ein verbindlicher nationaler SNOMED-CT-Katalog, der diese Informationen codiert. [FHIR.ch](http://fhir.ch/) bietet einen solchen Katalog bereits an.

Im PDMS ICM der Firma Dräger verwenden wir bereits in Ermangelung einer nationalen Ressource, diesen Katalog. Nur wäre der Austausch mit dem KIS, einem KAS, einem AMTS oder der elektronischen Gesundheitskarte des Patienten absolut erstrebenswert. Mit unserem Partner NursIT und deren Produkt CareIT IC übertragen wir auf diese Weise bereits Allergiedaten des Patienten aus dem Intensiv-/OP-Aufenthalt.

Wir bitten darum, diese Anforderung schnellstmöglich in die Roadmap-Planung mit aufzunehmen. Ggf. kann dies auch ein Unterpunkt in dem geplanten AMTS-Profil sein. Aber eigentlich ist diese Ressource so wichtig, daß sie eine eigene Betrachtung benötigt…
```[tasklist]
### Tasks
- [ ] PTDATA-686
```

**Comment by MaxMTheilig** [comment]
SNOMED-DE Version wurde veröffentlich.
An der Kommunikation zu AMTS wird in Stufe 4 Medikation gearbeitet
